### ISSUE TITLE
UI-Design: Create notifications page for mobile

### ISSUE THREAD

**Issue by deandrebaker** [Team-uMigrate/umigrate#141]
We need to create a prototype for the notifications page. New notifications should show up at the top, and should have AT LEAST the following information:
1. Creator of the notification
2. Type of notification (posts, ad, message, etc.)
3. Date and time

More information may be needed for each notification item

**Comment by dharinirajah** [comment]
![image](https://user-images.githubusercontent.com/52252036/94323185-b013bb00-ff49-11ea-854f-e94825943f18.png)


Notes : 

- Greyed out if the user has selected and read the notification
- Bolded name if the notification hasn't been read
- There should be an option to swipe instead of have to reach for the arrow key
- 3 ellipses for more > go to post, block user, mute notifications etc.,

**Comment by dharinirajah** [comment]
Updated titles : 
![image](https://user-images.githubusercontent.com/52252036/94759175-0de24180-0354-11eb-9a80-ac89cb1d94d2.png)

Examples of what you would see under notifications for each type of post.
